temp_folder: /home/user/tmpb/
target_package_folder : /home/user/amq-b-master

karaf_ssh_port: 8101
http_port: 8181
rmi_server_port: 44444
rmi_registry_port: 1099

amq_broker_name: amq-b-master
amq_openwire_port: 61616
amq_data_store_folder: /nfs/amq-b-store

networked_hosts:
  -  connect_to_host: amq-a
     master: amq-a-master
     slave: amq-a-slave
